version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01 # pins image to specific version

    steps:
      - checkout

      - run:
          name: Build container
          command: make build-for-tests

      - run:
          name: ESLint
          command: make eslint

      - run:
          name: Run tests
          command: make test-ci